name: cpm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.1.0
  - absl-py=0.12.0
  - albumentations=0.5.2
  - astor=0.8.1
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.1.19
  - cairo=1.16.0
  - certifi=2020.12.5
  - cloudpickle=1.6.0
  - coverage=5.5
  - cudatoolkit=10.1.243
  - cudnn=7.6.5.32
  - cupti=10.1.168
  - cycler=0.10.0
  - cython=0.29.22
  - cytoolz=0.11.0
  - dask-core=2021.3.0
  - dbus=1.13.18
  - decorator=4.4.2
  - dlib=19.21.1
  - expat=2.2.10
  - ffmpeg=4.3.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gast=0.4.0
  - geos=3.8.0
  - gettext=0.19.8.1
  - glib=2.68.0
  - glib-tools=2.68.0
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - grpcio=1.36.1
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.4
  - h5py=2.10.0
  - harfbuzz=2.8.0
  - hdf5=1.10.6
  - icu=68.1
  - imageio=2.9.0
  - imgaug=0.4.0
  - importlib-metadata=3.7.3
  - jasper=1.900.1
  - jpeg=9d
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.1
  - krb5=1.17.1
  - lame=3.100
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.75.0
  - libedit=3.1.20210216
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.3.0
  - libglib=2.68.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.43.0
  - libopencv=4.5.0
  - libpng=1.6.37
  - libpq=13.1
  - libprotobuf=3.14.0
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxkbcommon=1.0.3
  - libxml2=2.9.10
  - llvm-openmp=11.1.0
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2020.4
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - mysql-common=8.0.23
  - mysql-libs=8.0.23
  - ncurses=6.2
  - nettle=3.6
  - networkx=2.5
  - ninja=1.10.2
  - nspr=4.30
  - nss=3.63
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - opencv=4.5.0
  - openh264=2.1.1
  - openssl=1.1.1j
  - pcre=8.44
  - pillow=8.1.2
  - pip=21.0.1
  - pixman=0.40.0
  - protobuf=3.14.0
  - py-opencv=4.5.0
  - pyparsing=2.4.7
  - python=3.7.9
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.6.0
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - qt=5.12.9
  - readline=8.1
  - scikit-image=0.16.2
  - scipy=1.5.2
  - setuptools=52.0.0
  - shapely=1.7.1
  - six=1.15.0
  - sqlite=3.35.2
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - termcolor=1.1.0
  - tk=8.6.10
  - toolz=0.11.1
  - torchvision=0.7.0
  - tornado=6.1
  - tqdm=4.55.1
  - typing_extensions=3.7.4.3
  - werkzeug=1.0.1
  - wheel=0.36.2
  - wrapt=1.12.1
  - x264=1!161.3030
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.2
  - xorg-libx11=1.7.0
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - blend-modes
    - efficientnet-pytorch
    - future
    - munch
    - pretrainedmodels
    - segmentation-models-pytorch

